### ISSUE TITLE
MA Gateway using unsuported PUT Method

### ISSUE THREAD

**Issue by Kingkarule** [markusfeist/FhemMobileAlerts#38]
Hi, 
I am getting the following error in FHEM:

2020.12.28 16:40:29 3: WEB_192.168.0.35_2638: unsupported HTTP method PUT, rejecting it.

**Comment by markusfeist** [comment]
Hi,
according to the error message, I suspect that there is a configuration error. The message comes from the web module and not from MOBILEALERTSGW. Its message would be like this:
<Name Modul> **MOBILEALERTSGW:** <Name Modul>_<IP Gateway>_<Port>: unsupported HTTP method <Method>, rejecting it.

Your message seems to come from the normal FHEM web component, so the gateway seems to be sending to the wrong port.
You have to define a port in the configuration of the MOBILEALERTSGATEWAY component that is not the same as the normal FHEM port. So e.g. if FHEM is running on port 8083, e.g. 9001. Then you need to set the gateway to the correct port.

Markus

**Comment by Kingkarule** [comment]
Hi, 

thanks for the Help... the connection seem to work, but now another error is thrown:

2021.01.02 13:26:40 1: PERL WARNING: Use of uninitialized value $gateway in pattern match (m//) at ./FHEM/50_MOBILEALERTSGW.pm line 100.
2021.01.02 13:26:40 1: PERL WARNING: Use of uninitialized value $gateway in pattern match (m//) at ./FHEM/50_MOBILEALERTSGW.pm line 105.
2021.01.02 13:26:40 3: MobileAlertsGW MOBILEALERTSGW: Create UDP Socket.

**Comment by Kingkarule** [comment]
It's working after the second connection:

2021.01.02 13:32:04 2: autocreate: define MA_02181c52dedd MOBILEALERTS 02181c52dedd
2021.01.02 13:32:04 3: MA_02181c52dedd MOBILEALERTS: DeviceID 02181c52dedd
2021.01.02 13:32:05 2: autocreate: define FileLog_MA_02181c52dedd FileLog ./log/MA_02181c52dedd-%Y.log MA_02181c52dedd
2021.01.02 13:32:05 1: PERL WARNING: Use of uninitialized value $gplot in concatenation (.) or string at ./FHEM/98_autocreate.pm line 283.

Still throwing a warning, but does not look critical.

Thanks

**Comment by markusfeist** [comment]
The warnings are all uncritical, but ugly. I've made a fix and will check it in to FHEM with the next version.
